/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package remove;

import DAO.AlunoDAO;
import DAO.AutorDAO;
import DAO.EditoraDAO;
import DAO.LivroDAO;
import DAO.PessoaDAO;
import DAO.ProfessorDAO;
import DAO.TelefoneDAO;
import bidi.Aluno;
import bidi.Autor;
import bidi.Editora;
import bidi.Livros;
import bidi.Pessoa;
import bidi.Professor;
import bidi.Telefone;
import javax.swing.JOptionPane;
import repositorio.RepositorioAluno;
import repositorio.RepositorioAutor;
import repositorio.RepositorioEditora;
import repositorio.RepositorioLivro;
import repositorio.RepositorioPessoa;
import repositorio.RepositorioProfessor;
import repositorio.RepositorioTelefone;

/**
 *
 * @author neto
 */
public class TelaRemover extends javax.swing.JFrame {

    /**
     * Creates new form TelaRemover
     */
    public TelaRemover() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        txtAluno = new javax.swing.JTextField();
        txtEditora = new javax.swing.JTextField();
        txtLivro = new javax.swing.JTextField();
        txtProfessor = new javax.swing.JTextField();
        btnRemAutor = new javax.swing.JButton();
        btnRemAluno = new javax.swing.JButton();
        btnRemEditora = new javax.swing.JButton();
        btnRemLivro = new javax.swing.JButton();
        btnRemProf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remover");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel1.setText("ID do autor:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel2.setText("CPF do aluno:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel3.setText("ID da editora:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel4.setText("ISBN do livro:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel5.setText("CPF do professor:");

        txtAutor.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        txtAluno.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        txtEditora.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        txtLivro.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        txtProfessor.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        btnRemAutor.setText("Remover autor");
        btnRemAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemAutorActionPerformed(evt);
            }
        });

        btnRemAluno.setText("Remover aluno");
        btnRemAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemAlunoActionPerformed(evt);
            }
        });

        btnRemEditora.setText("Remover editora");
        btnRemEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemEditoraActionPerformed(evt);
            }
        });

        btnRemLivro.setText("Remover livro");
        btnRemLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemLivroActionPerformed(evt);
            }
        });

        btnRemProf.setText("Remover Professor");
        btnRemProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemAutor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                        .addComponent(btnRemProf))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemAluno))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemEditora))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemLivro)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemAutor))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemAluno))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemEditora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemLivro))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemProf))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemAutorActionPerformed
        String idAutor = txtAutor.getText();
        int idaut = Integer.parseInt(idAutor);
        
        Autor a = new Autor();
        a.setId_autor(idaut);
        
        RepositorioAutor re1 = new AutorDAO();
        if(re1.buscarAutor(idaut) != null){
            re1.removerAutor(a);
        }
    }//GEN-LAST:event_btnRemAutorActionPerformed

    private void btnRemAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemAlunoActionPerformed
        String cpf = txtAluno.getText();
        
        Aluno a = new Aluno();
        a.setCpf(cpf);
        
        Pessoa p = new Pessoa();
        p.setCpf(cpf);
        
        RepositorioAluno repA = new AlunoDAO();
        RepositorioPessoa repP = new PessoaDAO();
        
        if(repA.buscarAluno(cpf) != null){
            if(repP.buscarPessoa(cpf) != null){
                repA.removerAluno(a);
                repP.removerPessoa(p);
            }
        }
    }//GEN-LAST:event_btnRemAlunoActionPerformed

    private void btnRemEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemEditoraActionPerformed
        String id = txtEditora.getText();
        int idd = Integer.parseInt(id);
        
        Editora e = new Editora();
        e.setId_editora(idd);
        
        RepositorioEditora rep = new EditoraDAO();
        if(rep.buscarEditora(idd) != null){
            rep.removerEditora(e);
        }
    }//GEN-LAST:event_btnRemEditoraActionPerformed

    private void btnRemLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemLivroActionPerformed
        String isn = txtLivro.getText();
        
        Livros l = new Livros();
        l.setISBN(isn);
        
        RepositorioLivro rep = new LivroDAO();
        if(rep.buscarLivro(isn) != null){
            rep.removerLivro(l);
        }
    }//GEN-LAST:event_btnRemLivroActionPerformed

    private void btnRemProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemProfActionPerformed
        String cpf = txtProfessor.getText();
        
        Professor a = new Professor();
        a.setCpf(cpf);
        
        Pessoa p = new Pessoa();
        p.setCpf(cpf);
        
        RepositorioProfessor repA = new ProfessorDAO();
        RepositorioPessoa repP = new PessoaDAO();
        
        if(repA.buscarProfessor(cpf) != null){
            if(repP.buscarPessoa(cpf) != null){
                repA.removerProfessor(a);
                repP.removerPessoa(p);
            }
        }
    }//GEN-LAST:event_btnRemProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRemover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemAluno;
    private javax.swing.JButton btnRemAutor;
    private javax.swing.JButton btnRemEditora;
    private javax.swing.JButton btnRemLivro;
    private javax.swing.JButton btnRemProf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAluno;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtLivro;
    private javax.swing.JTextField txtProfessor;
    // End of variables declaration//GEN-END:variables
}
